lab02/calculadora/urls.py
from django.urls import path
from . import views

app_name = 'calculadora'

urlpatterns = [
    # ex:/calculadora/
    path('', views.index, name='index'),
    path('calcular', views.calcular, name='calcular'),
]

lab02/cilindro/urls.py
from django.urls import path
from . import views

app_name = 'cilindro'

urlpatterns = [
    # ex:/cilindro/
    path('', views.index, name='index'),
    path('calcular', views.calcular, name='calcular'),
]

lab02/encuesta/urls.py
from django.urls import path
from . import views

app_name = 'encuesta'

urlpatterns = [
    # ex:/encuesta/
    path('', views.index, name='index'),
    path('enviar', views.enviar, name='enviar'),
]

lab02/lab02/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('encuesta/', include('encuesta.urls')),
    path('calculadora/', include('calculadora.urls')),
    path('cilindro/', include('cilindro.urls')),
    path('admin/', admin.site.urls),
]

lab02/calculadora/views.py
from django.shortcuts import render

# Create your views here.


def index(request):
    context = {
        'titulo': "Formulario de operaciones",
    }
    return render(request, 'calculadora/formulario.html', context)


def calcular(request):
    if request.method == 'POST':
        num1 = int(request.POST['num1'])
        num2 = int(request.POST['num2'])
        operacion = request.POST['operacion']

        if operacion == 'suma':
            respuesta = num1 + num2
            signo = '+'
        elif operacion == 'resta':
            respuesta = num1 - num2
            signo = '-'
        elif operacion == 'multiplicacion':
            respuesta = num1 * num2
            signo = 'x'

        context = {
            'num1': num1,
            'num2': num2,
            'operacion': operacion,
            'signo': signo,
            'respuesta': respuesta,
        }

        return render(request, 'calculadora/respuesta.html', context)

lab02/cilindro/views.py
from django.shortcuts import render

# Create your views here.


def index(request):
    context = {
        'titulo': "CÁLCULO DEL VOLUMEN DE UN CILINDRO",
    }
    return render(request, 'cilindro/formulario.html', context)


def calcular(request):
    altura = float(request.POST['altura'])
    diametro = float(request.POST['diametro'])
    radio = diametro / 2
    volumen = round(altura * 3.1416 * radio ** 2, 4)
    context = {
        'titulo': 'Resultado del cálculo',
        'altura': altura,
        'diametro': diametro,
        'volumen': volumen,
    }
    return render(request, 'cilindro/resultado.html', context)

lab02/encuesta/views.py
from django.shortcuts import render

# Create your views here.


def index(request):
    context = {
        'titulo': "Formulario",
    }
    return render(request, 'encuesta/formulario.html', context)


def enviar(request):
    context = {
        'titulo': "Respuesta",
        'nombre': request.POST['nombre'],
        'clave': request.POST['password'],
        'educacion': request.POST['educacion'],
        'nacionalidad': request.POST['nacionalidad'],
        'idiomas': request.POST.getlist('idiomas'),
        'correo': request.POST['email'],
        'website': request.POST['sitioweb'],
    }
    return render(request, 'encuesta/respuesta.html', context)

lab02/calculadora/templates/calculadora/formulario.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8" />
    <title>Formulario de operaciones</title>
  </head>

  <body>
    <h1>{{titulo}}</h1>
    <form action="{% url 'calculadora:calcular' %}" method="post">
      {% csrf_token %}
      <label for="num1">Primer número:</label>
      <input type="number" name="num1" required /><br /><br />
      <label for="num2">Segundo número:</label>
      <input type="number" name="num2" required /><br /><br />
      <label for="operacion">Operación:</label>
      <select name="operacion" required>
        <option value="">Seleccione una operación</option>
        <option value="suma">Suma</option>
        <option value="resta">Resta</option>
        <option value="multiplicacion">Multiplicación</option></select
      ><br /><br />
      <input type="submit" name="submit" value="Calcular" />
    </form>
  </body>
</html>

lab02/calculadora/templates/calculadora/respuesta.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8" />
    <title>Resultado de la operación</title>
  </head>

  <body>
    <h1>Resultado de la operación</h1>
    <p>
      La {{ operacion }} de {{ num1 }} {{signo}} {{ num2 }} = {{respuesta }}
    </p>
  </body>
</html>

lab02/cilindro/templates/cilindro/formulario.html
<!DOCTYPE html>
<html>
  <head>
    <title>Formulario-Cilindro</title>
    <style>
      .forml {
        margin-left: 80px;
        margin-top: 50px;
      }
    </style>
  </head>

  <body>
    <div class="forml">
      <h2>{{ titulo }}</h2>
      <form action="{% url 'cilindro:calcular' %}" method="post">
        {% csrf_token %}

        <label for="diametro"
          ><b>Introduzca el diámetro en metros</b> <small>(3.12):</small>
        </label>
        <input
          type="number"
          step="any"
          id="diametro"
          name="diametro"
          required
        /><br /><br />
        <label for="altura"
          ><b>Introduza la altura en metros</b> <small>(2.24):</small>
        </label>
        <input
          type="number"
          step="any"
          id="altura"
          name="altura"
          required
        /><br /><br />
        <input type="submit" value="Calcular" />
      </form>
    </div>
  </body>
</html>

lab02/cilindro/templates/cilindro/resultado.html
<!DOCTYPE html>
<html>
  <head>
    <title>Resultado-cilindro</title>
  </head>
  <body>
    <h2>{{ titulo }}</h2>
    <small
      ><p>Altura: {{ altura }} m</p>
      <p>Diámetro: {{ diametro }} m</p>
    </small>
    <p>El volumen del cilindro es de {{ volumen }} metros cúbicos</p>
  </body>
</html>

lab02/encuesta/templates/encuesta/formulario.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Formulario</title>
</head>

<body>
    <h2>{{titulo}}</h2>
    <form action="{% url 'encuesta:enviar' %}" method="post">
        {% csrf_token %}

        Nombre:
        <input type="text" name="nombre" maxlength="50" /> <br />
        Contraseña:
        <input type="password" name="password" /> <br />
        Educacion:
        <select name="educacion">
            <option value="sin-estudios">Sin estudios</option>
            <option value="educacion-obligatoria" selected="selected">
                Educacion Obligatoria
            </option>
            <option value="formacion-profesional">Formacion profesional</option>
            <option value="universidad">Universidad</option>
        </select><br />
        Nacionalidad:
        <input type="radio" name="nacionalidad" value="hispana">Hispana</input>
        <input type="radio" name="nacionalidad" value="otra">Otra</input> <br>
        Idiomas:
        <input type="checkbox" name="idiomas" value="español" checked="checked">Español</input>
        <input type="checkbox" name="idiomas" value="ingles">Ingles</input>
        <input type="checkbox" name="idiomas" value="frances">Frances</input>
        <input type="checkbox" name="idiomas" value="aleman">Aleman</input> <br>
        Email:
        <input type="text" name="email"><br>
        Sitio Web:
        <input type="text" name="sitioweb"><br>
        <!-- Boton de enviar  -->
        <input type="submit" name="submit" value="Enviar">
    </form>
</body>

</html>

lab02/encuesta/templates/encuesta/respuesta.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Formulario</title>
  </head>

  <body>
    <h2>{{titulo}}</h2>
    <p>Nombre: {{nombre}}</p>
    <p>Clave: {{clave}}</p>
    <p>Educacion: {{educacion}}</p>
    <p>Nacionalidad: {{nacionalidad}}</p>
    <p>Idiomas:</p>
    <ul>
      {% for item in idiomas %}
      <li>{{item}}</li>
      {% endfor %}
    </ul>
    <p>Email: {{correo}}</p>
    <p>Sitio Web: {{website}}</p>
  </body>
</html>